### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by awais-amjed** [awais-amjed/catalog-of-my-things#20]
## Project [link](https://github.com/awais-amjed/catalog-of-my-things/projects/1)
# There are 3 people on our team.

- Team Member 1: [Dire Akanbi](https://github.com/direakanbi)
- Team Member 2: [Awais Amjed](https://github.com/awais-amjed)
- Team Member 3: [Dagmawi zewdu](https://github.com/Dagic-zewdu)

**Comment by medaminedev66** [comment]
Hi team  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Each card in your Kanban board should have the number of points in the \[Xpt\] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work. Check out the example below:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/77190203/169792376-9329d63b-9930-415b-b322-704e3465b6de.png">

Please work on that.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by awais-amjed** [comment]
Thanks for the feedback, We updated the project with points.

**Comment by dasileker** [comment]
### **Hi @awais-amjed,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
